[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pyDiaglib"
version = "1.0.0"
authors = [
  { name="Ivan Giannì", email="ivangianni@live.it" },
]
description = "DiagLib python interface"
requires-python = ">=3.9"
dependencies = ["numpy"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["pyDiaglib"]
