[extra.ford]
project = "DiagLib"
author = "I. Giannì, T. Nottoli, R. Alessandro, D. Cianchino, L. Lapi, F. Lipparini"

src_dir = "../src"
output_dir = "../doc"
page_dir = "./pages"
media_dir = "."

exclude_dir = "../src/c_interface"
exclude = "../src/fortran/diaglib.f90"

graph = false
sort = "type-alpha"