[extra.ford]
project = "DiagLib"
summary = "### A collection of matrix-free iterative eigensolvers"
author = """
I. Giannì,
T. Nottoli,
R. Alessandro,
D. Cianchino,
L. Lapi,
F. Pes,
A. Levitt,
F. Lipparini
"""
author_description = "MolecoTheory subgroup of MolecoLab and collaborators"
email = "filippo.lipparini@unipi.it"

src_dir = "../src"
output_dir = "../doc"
page_dir = "./pages"
media_dir = "."

exclude_dir = "../src/c_interface"
exclude = "../src/fortran/diaglib.f90"

graph = false
sort = "type-alpha"
max_frontpage_items = 4
#display = "public protected private"